title: 时间和我都在往前走
description: 时间和我都在往前走
author: yang
github: https://github.com/xilankong
about: 时间和我都在往前走
disqus_shortname: 时间和我都在往前走
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: /static/img/github.png
      link: "https://github.com/xilankong"
    - icon: /static/img/mail.png
      link: "mailto:xilankong@126.com"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: iOS开发基础
      url: /category/iOS开发基础
    - text: iOS开发进阶
      url: /category/iOS开发进阶
    - text: iOS性能优化
      url: /category/iOS性能优化
    - text: iOS关键词复习法
      url: /category/iOS关键词复习法
    - text: 关于我
      url: /about/

url: "https://xilankong.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
